export const SWITCH_REGISTER = 'SWITCH_REGISTER';

export const SHOW_HDIE_LOADING = 'SHOW_HIDE_LOADING';

export const LOGIN_BEGIN = 'LOGIN_BEGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCSESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const REGISTER_BEGIN = 'REGISTER_BEGIN';
export const REGISTER_SUCCESS = 'REGISTER_SUCSESS';
export const REGISTER_ERROR = 'REGISTER_ERROR';
